/*
 * REST Petclinic backend Api Documentation
 * This is REST API documentation of the Spring Petclinic backend. If authentication is enabled, when calling the APIs use admin/admin
 *
 * OpenAPI spec version: 1.0
 * Contact: vitaliy.fedoriv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 7.2.0
 */

import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://localhost:9966/petclinic";

// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.
export let options = {
  stages: [
    { duration: "0.5m", target: 3 }, // simulate ramp-up of traffic from 1 to 3 virtual users over 0.5 minutes.
    { duration: "0.5m", target: 2000 }, // stay at 4 virtual users for 0.5 minutes
    { duration: "0.5m", target: 6 }, // start reducng usage for 0.5 minutes
    { duration: "0.5m", target: 0 }, // ramp-down to 0 users
  ],
};

export default function () {
  group("List all vets", () => {
    // Request: listVets
    {
      let url = BASE_URL + `/api/vets`;
      let request = http.get(url);

      check(request, {
        "Vets found and returned.": (r) => r.status === 200,
      });

      sleep(SLEEP_DURATION);
    }
  });

  group("Create vets", () => {
    // Request: addVet
    {
      let url = BASE_URL + `/api/vets`;

      let body = {
        firstName: "James",
        lastName: "Carter",
        specialties: [
          {
            name: "radiology",
          },
        ],
      };
      let params = { headers: { "Content-Type": "application/json", Accept: "application/json" } };
      let request = http.post(url, JSON.stringify(body), params);

      check(request, {
        "Vet created successfully.": (r) => r.status === 201,
      });
    }
  });
}
